### ISSUE TITLE
wrong area calculated for tetra-sphere intersection

### ISSUE THREAD

**Issue by aguirreeng** [severinstrobl/overlap#11]
Hello, I was testing the code and I have found that for the following set of inputs, the area calculated is wrong (even negative).

```cpp
#include <iostream>
#include "../overlap.hpp"

int main(void) {
    // Sphere data:
    double radius = 0.25;
    vector_t center { 0.5, 0.5, 1.0 };
    Sphere sphere{ center, radius };

    // Tetrahedron vertices.
    vector_t node0 { 0.807798, 0.649062, 1.072417 };
    vector_t node1 { 0.804911, 0.511303, 0.962443 };
    vector_t node2 { 0.687459, 0.655182, 0.976268 };
    vector_t node3 { 0.681356, 0.534586, 1.056372 };
    Tetrahedron tetra{ node0, node1, node2, node3 };
    
    auto intersect_area = overlapArea(sphere, tetra);
  
    for (auto& area: intersect_area) {
        std::cout << area << std::endl;
    }
}
```

The expected value for the sphere section is around 0.0065m² but the output from the function is -0.160697m², the area of the tetrahedron face sections also does not match the expected data.

**Comment by aguirreeng** [comment]
Ops, my bad, nevermind. 

Your algorithm/code requires that the tetrahedron faces are described in an order which sets the normal vectors pointed inward to the tetrahedron. The one I have specified here was defined with normals pointing outward the tetra.

Nice paper by the way. cheers.

**Comment by severinstrobl** [comment]
Thanks and sorry for the confusion, I really should document the input format explicitly.

**Comment by jdema** [comment]
Hello, I have found myself having this same problem with the Python implementation of this code, but am not sure I understand the solution described in the comment above. Could someone expand on the proper order of vertex input for tetrahedral mesh elements?

**Comment by severinstrobl** [comment]
The ordering of the vertices has to follow the conventions used by CGNS, in the case of tetrahedra: https://cgns.github.io/CGNS_docs_current/sids/conv.html#unst_tetra

**Comment by severinstrobl** [comment]
@jdema: Did this help you getting the code to work, or does the issue persist?
