### ISSUE TITLE
Overlap area of sphere inside of tetrahedron

### ISSUE THREAD

**Issue by wesbarnett** [severinstrobl/overlap#5]
I am attempting to use this program to calculate the overlap area of a tetrahedron and a sphere (the example in the README). I notice that it gives the overlap area for each tetrahedron face and sums that up as the total overlap area. Is there also a way to return the overlap area of the sphere (that is, the area of the spherical cap residing inside the tetrahedron)?

**Comment by severinstrobl** [comment]
While I started working on this a while ago, this is currently not supported. I have to find an analytical solution to a certain integral in order to perform a decomposition analogous to the one used for the volume calculation.
