### ISSUE TITLE
Incompatible license with STEPS future goals

### ISSUE THREAD

**Issue by iahepburn** [severinstrobl/overlap#96]
Dear @severinstrobl , 

Firstly, thank you for this awesome overlap library which we use in the STEPS project (https://github.com/CNS-OIST/STEPS), specifically for calculating overlap between simulated vesicles and our tetrahedral meshes, as described in: https://www.nature.com/articles/s42003-024-06276-5

When including your project under the GPL this means that STEPS also has to be released under GPL, as it is currently. However, this is incompatible with future plans of STEPS, which include being released as open source software for neural simulation by the Blue Brain Project (https://www.epfl.ch/research/domains/bluebrain/) or its successor. Blue Brain project developer https://github.com/tristan0x will be able to provide more details on these goals. 

So, this is quite an issue for us because we rely on your library yet with no license change we wouldn't be able to use it in the future and would have to come up with an alternative. By far our preference is to continue using your library, which would however require a change of license. So I just wanted to open this discussion and ask, would you be open in principle to potentially changing the license for the overlap library to one that is compatible with our future plans? We will provide more details on our plans, and can put forward licenses that would be compatible for us for your consideration if so. Thank you.

**Comment by severinstrobl** [comment]
Hi @iahepburn, happy to hear you find this library useful for your works. Funnily enough, there was a very similar request from a different group looking to combine this library with their own works. This resulted in a change of the development version of overlap to the MIT license (see #92). While it might still take some time for me to implement and integrate all the changes I would like to see for an official 0.2 release, the library itself is in a quite robust state. Is the MIT license compatible with your plans?

**Comment by tristan0x** [comment]
Thank you very much for your reply @severinstrobl 
MIT license for the future 0.2 release would be perfect indeed.
We will take a look at the _develop_ version of overlap. Do you plan to refactor the public API or will 0.2 look like the current state of _develop_?
Thank you again for this library

**Comment by severinstrobl** [comment]
@tristan0x: Please excuse the delayed response. I don't expect further changes to the public API for the 0.2 release, so basing your work on the current _develop_ version should make the switch to the 0.2 release trivial.

**Comment by severinstrobl** [comment]
Hi @iahepburn, indeed you found a regression introduced in the development version of the library. The problem is not the initial scale of the sphere/tetrahedron, before processing a scaling of all coordinates resulting in a unit sphere centered at the origin is performed. Nevertheless, you are absolutely correct about the problem in the normal calculation you identified. I'm surprised this did not break any of the existing test cases.
Either way, thank you for providing the test case which helped me to quickly reproduce the issue!

**Comment by iahepburn** [comment]
Thank you @severinstrobl for this quick fix. Yes, all seems to be working well now. I think we can close the issue.
